### PR TITLE
Use the default compiler on Travis CI

### PR DESCRIPTION
**Pull request by jasonrudolph**
CI is [currently failing on the master branch](https://travis-ci.org/tree-sitter/tree-sitter-json/builds/461924279). Let's fix that.

This same change seemed to get CI working again in tree-sitter-javascript (https://github.com/tree-sitter/tree-sitter-javascript/commit/aeb4399be10d80c5aac5880e9a75541494d335fb), so let's try it for tree-sitter-json.

### CODE REVIEW

**Comment by jasonrudolph** [comment]
> ... let's try it for tree-sitter-json.

No dice. 😭 

https://travis-ci.org/tree-sitter/tree-sitter-json/builds/535837088

**Comment by maxbrunsfeld** [comment]
Oh, I think we may need to upgrade to `tree-sitter-cli` version 0.14.x. This is still using the old C++ one.

**Comment by maxbrunsfeld** [comment]
Sorry about the mess here @jasonrudolph; I never really used this repo for anything (except for testing) until now.

**Comment by jasonrudolph** [comment]
> Oh, I think we may need to upgrade to `tree-sitter-cli` version 0.14.x. This is still using the old C++ one.

Thanks, @maxbrunsfeld. I'll look into that shortly. :bow:

**Pull request merged**
